### PR TITLE
Fix add `devise :omniauthable` to `Spree::User`

### LINKED ISSUE #20: Error: "Please add devise :omniauthable"
Hi everyone!

Thanks for the great gem. I'm getting this little error every once in a while.

`Mapping omniauth_callbacks on a resource that is not omniauthable Please add`devise :omniauthable`to the`Spree::User`model`

Then, afterwards (sometimes), an entire multitude of stuff appears. One example:
`undefined method`nested_taxons_path' for #ActionDispatch::Routing::RoutesProxy:0x007fb15e9e5068``
 (simply on the root, out of nowhere)

Rails 5. Freshly new Solidus installation, everything by the book, nothing special. I restart the server, everything goes back to normal. I work some more, make some small changes and... This.

I don't get it.

### PR DESCRIPTION
**Pull request by qr8r**
Fix #20 

## Problem:
Devise error when 'hot' reloading code.

## Cause:
Rails 5 constant reloading loads routes before running the application
to_prepare block.

Solidus Social defines omniauth routes via devise which requires
Spree::User to have the `:omniauthable` attributes.

Our application and many gems apply their solidus
decorators from within the to_prepare block. This was the case for
solidus social decorating Spree::User to include the :omniauthable
attribute.

When rails would attempt to reload the environment constants, it would
unload the spree user constant (removing any previous decorations) and
then attempt to generate routes for (including the omniauth routes
defined in solidus_social). At this time, an error would be thrown since
the Spree::User class was missing the decorator required to draw these
routes.

## Solution:
Add an initializer which forces the solidus_social user decorator to be
loaded immediately after rails unloads existing constants during the
constant reload process.

## Testing:
1. To see the error checkout master and run `bundle exec rails c` (in the
  dummy store)
2. once in the pry environment run `reload!`
3. You should see the error

4. Checkout this branch
5. repeat the steps above
6. You should not receive any errors and be able to reload the rails
  environment

### CODE REVIEW

File: lib/solidus_social/engine.rb [hunk 1]
```diff
@@ -16,6 +16,16 @@ class Engine < Rails::Engine
       Spree::SocialConfig = Spree::SocialConfiguration.new
     end
 
+    initializer 'solidus_social.decorate_spree_user' do
+      Rails.application.reloader.after_class_unload do
+        # Reload and decorate the spree user class immediately after it is
+        # unloaded so that it is available to devise when loading routes
+        if Rails.configuration.cache_classes == false
```
Comment (jarednorman) [inline lib/solidus_social/engine.rb]: I think you mean `unless Rails.configuration.cache_classes` :wink:

**Review by jarednorman — CHANGES_REQUESTED** [review]

File: lib/solidus_social/engine.rb (hunk 1 above)
Comment (qr8r) [reply lib/solidus_social/engine.rb]: Haha right ... learn 2 ruby.

I also realized when patching this into our app directly that that check is rather redundant, since the after_class_unload callback is only run when caching is disabled anyway

**Review by jarednorman — APPROVED** [review]

**Comment by jarednorman** [comment]
The CI failures look related to this change, can you take a look?

**Comment by jarednorman** [comment]
@brendandeere Am I good to merge this now?

**Comment by qr8r** [comment]
@jarednorman Yep!
